export const Color = {
  bluePrimary: '#0A0F12',
  blueSecondary: '#152040',
  blueTertiary: '#A2B8DB',
  blueQuartenary: 'rgba(45, 210, 255, 0.1)',
  blueSenary: '#111B39',
  cyanPrimary: '#2DD2FF',
  cyanSecondary: '#77D3F1',
  cyanTertiary: '#70B6DE',
  cyanQuartenary: '#76c9df',
  cyanSenary: '#28E6F4',
  whitePrimary: '#ffffff',
  blackPrimary: '#000000',
  blackSecondary: 'rgba(0, 0, 0, 0.8)',
  primaryRed: '#FF4646',
  yellowPrimary: '#826B49',
  purplePrimary: '#16244e',
  lightBluePrimary: '#242E4C',
  darkBluePrimary: '#010C2A',
  purple: '#293A99',
  purpleSecondary: '#b9c1d9',
  ethereumColor: '#627EEA',
  binanceColor: '#F6C748',
  maticColor: '#8F5AE8',
  grayPrimary: '#0A0F12',
  graySecondary: 'rgba(255, 255, 255, 0.1)',
  grayThird: '#444952',
  grayFour: '#3D3F43',
  darkPrimary: '#9AA1AC',
  darkSecondary: '#23272E',
  lightGrayPrimary: '#A0A5AD',
  darkGray: '#333333'
};

export const Theme = {
  headerBackground: Color.grayPrimary,
  linkColor: Color.whitePrimary,
  linkBorder: Color.lightBluePrimary,
  primaryPageBg: Color.blackPrimary,
  secondaryPageBg: Color.darkBluePrimary,
  primaryBackground: Color.purple,
  textColorPrimary: Color.darkPrimary,
  textColorSecondary: Color.cyanSecondary,
  textColorTertiary: Color.blueTertiary,
  borderPrimary: Color.grayThird,
  borderSecondary: Color.grayFour,
  buttonPrimaryBg: 'linear-gradient(180deg, #25D9FD 0%, #2CFEE1 100%)',
  buttonPrimaryColor: Color.whitePrimary,
  buttonSecondaryBg: Color.graySecondary,
  buttonBorderRadius: '30px',
  buttonBoxShadowPrimary: '0px 0px 10px rgba(45, 210, 255, 0.4)',
  error: Color.primaryRed,
  modalBg: Color.blackSecondary,
  modalShadow: '0px 0px 20px rgba(0, 0, 0, 0.4)',
  warning: Color.yellowPrimary,
  selectedWalletBg: Color.blueQuartenary,
  elementBorderRadius: '8px',
  eleOutBorderRadius: '10px',
  componentBorderRadius: '12px',
  compOutBorderRadius: '14px',
  sidebarBg: Color.blackPrimary,
  graphColorPrimary: '#576DFF',
  graphColorSecondary: '#2CFEE1',
  disabledButton:
    'linear-gradient(180deg, rgba(37, 217, 253, 0.4) 0%, rgba(44, 254, 225, 0.4) 100%)',
  backgroundColor: 'linear-gradient(120.36deg,#191c21 - 2.08 %,#0b1014 71.5 %)',
  blackText: Color.blackPrimary,
  whiteText: Color.whitePrimary,
  grayText: Color.lightGrayPrimary,
  darkBg: Color.darkPrimary,
  cardBg: Color.darkGray,
  inputTextBg: Color.darkSecondary,
  inputTextOpacity: '0.3'
};
