export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_ETH_BALANCE_SUCCESS = 'GET_ETH_BALANCE_SUCCESS';

export const STAKE_START = 'STAKE_START';

export const STAKE_SUCCESS = 'STAKE_SUCCESS';

export const UPDATE_USDT_BALANCE = 'UPDATE_USDT_BALANCE';

export const UPDATE_USDC_BALANCE = 'UPDATE_USDC_BALANCE';

export const UPDATE_DAI_BALANCE = 'UPDATE_DAI_BALANCE';

export const UPDATE_BUSD_BALANCE = 'UPDATE_BUSD_BALANCE';
